### ISSUE TITLE
API returning "No Username Found"

### ISSUE THREAD

**Issue by manuelgu** [Incrementing/MCUUID#4]
API returns "No Username Found" for field `name` for the majority of my users.

```java
Map<UUID, String> uuidStringMap = new HashMap<>();
private final JSONParser jsonParser = new JSONParser();
private final List<UUID> uuids;
for (UUID uuid : uuids) {
    HttpsURLConnection connection = (HttpsURLConnection) new URL("https://api.mcuuid.com/json/name/" + uuid.toString().replace("-", "")).openConnection();
    connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13");
    JSONObject response = (JSONObject) jsonParser.parse(new InputStreamReader(connection.getInputStream()));
    if (response == null) {
       continue;
    }
    String name = (String) response.get("name");
    if (name == null) {
        continue;
    }
    uuidStringMap.put(uuid, name);
}
```

` private final List<UUID> uuids;` is getting fed with UUIDs.

![](http://i.imgur.com/VrBS5JH.png)

**Comment by incrementing** [comment]
I'm currently out of town visiting family but I'll try help as best I can.
Do all the uuids return username not found or only some?

**Comment by incrementing** [comment]
Try without stripping away the dashes, that should work for now. I'll fix the bug that stops stripped UUIDs from working when I'm home.

**Comment by manuelgu** [comment]
I did that. 
![](http://i.imgur.com/1E0Dp36.png)
This is according to [your tweet](https://twitter.com/Incrementing/status/813729844932517888) returning a correct username for you, but not me.

**Comment by incrementing** [comment]
The issue should now be fixed. Sorry for any inconvenience caused.
